---
- name: Purge kolla environment
  hosts: all

  vars:
    destroy_include_images: false
    destroy_include_dev: false

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to purge the kolla environment?
      default: 'no'
      private: false

    - name: ireallyreallymeanit
      prompt: Are you really sure you want to purge the kolla environment?
      default: 'no'
      private: false

  tasks:
    - name: Exit playbook, if user did not mean to purge the kolla environment
      fail:
        msg: >
          "To purge the kolla environment, either say 'yes' and 'ireallyreallymeanit'
           on the prompt or use `-e ireallymeanit=yes` and
           `-e ireallyreallymeanit=ireallyreallymeanit` on the command line when
           invoking the playbook"
      when:
        - ireallymeanit != 'yes'
        - ireallyreallymeanit != 'ireallyreallymeanit'

    - name: Destroying all kolla containers and volumes
      script: cleanup-containers

    - name: Destroying kolla host configuration
      become: true
      script: cleanup-host
      environment:
        enable_haproxy: "{{ enable_haproxy }}"
        enable_swift: "{{ enable_swift }}"
        elasticsearch_datadir_volume: "{{ elasticsearch_datadir_volume|default('elasticsearch') }}"
        glance_file_datadir_volume: "{{ glance_file_datadir_volume|default('glance') }}"
        nova_instance_datadir_volume: "{{ nova_instance_datadir_volume|default('nova_compute') }}"
        gnocchi_metric_datadir_volume: "{{ gnocchi_metric_datadir_volume|default('gnocchi') }}"
        kolla_internal_vip_address: "{{ kolla_internal_vip_address }}"
        kolla_external_vip_address: "{{ kolla_external_vip_address }}"
        kolla_dev_repos_directory: "{{ kolla_dev_repos_directory|default('/opt/stack/') }}"
        destroy_include_dev: "{{ destroy_include_dev }}"

    - name: Removing kolla images
      script: cleanup-images --all
      when:
        - destroy_include_images|bool
